### ISSUE TITLE
change condition in time_point_thresh processor

### ISSUE THREAD

**Issue by mmatteo** [legend-exp/pygama#141]
https://github.com/legend-exp/pygama/blob/86c68084d631856d44b85e29ceca4ef0e98f7c50/pygama/dsp/_processors/time_point_thresh.py#L17

I think the condition above should be extended to include the case in which `wf_in[i]=threshold`. I would also return a nan if the condition is not met. This would be the new piece of code:
```
    for i in range(tp_max, 0, -1):
        if(wf_in[i]>=threshold and wf_in[i-1]<threshold):
            tp_out[0] = i
            return
    tp_out[0] = np.nan
    return
````

**Comment by mmatteo** [comment]
P.S. I open an issue instead of a PR to discuss the general concept. I can open a PR to change all processors affected after we agree.

**Comment by jasondet** [comment]
I agree with this.

**Comment by mmatteo** [comment]
thank @jasondet, I'll start reviewing the processors next week to fix all this issues
