### ISSUE TITLE
How to control when a progress bar is printed

### ISSUE THREAD

**Issue by sweigart** [legend-exp/pygama#152]
https://github.com/legend-exp/pygama/blob/ee80959d1944de92defacd5249fbdfb96e64c7a8/pygama/io/fcdaq.py#L451-L455
https://github.com/legend-exp/pygama/blob/ee80959d1944de92defacd5249fbdfb96e64c7a8/pygama/io/fcdaq.py#L502-L504

The `verbose` argument in `process_flashcam` conveniently controls whether extra information is printed out.  It also controls the printout of a progress bar (see the code snippets above).  While nice when running in one's terminal, this progress bar causes a lot of extraneous text to be saved when writing the output to a log file (as is typically done when, for instance, running remotely on a grid node).  For example:

`... ^MProgress : [#############-------] 66.3% ^MProgress : [#############-------] 66.3% ^MProgress : [#############-------] 66.4% ^MProgress : [#############-------] 66.4% ^MProgress : [#############-------] 66.4% ^MProgress : [#############-------] 66.4% ^MProgress : [#############-------] 66.4% ^MProgress : [#############-------] 66.4% ^M^MProgress : [#############-------] 66.5% ^MProgress : [#############-------] 66.5% ...`

The issue is that there is no way print out the extra information while not printing out the progress bar.  Currently, the `verbose` argument controls both.  I'm opening up an issue because I can imagine various ways to resolving it, but I'm willing to implement whatever approach is agreed upon.

As an example, one way would be to add a new (optional) argument in `process_flashcam`, say, `bar=False`.  The `update_progress` calls above would then be conditioned on `bar` being `True` (regardless to the value of `verbose`).  This hopefully wouldn't break people's code since an argument is being added, not changed or removed.

**Comment by jasondet** [comment]
I like the "bar=False" option. 

Another option is to use verbosity levels like we do elsewhere, except then you wouldn't be able to simultaneously support full verbosity but no bar as well as bar on but minimal verbosity.

Another option -- one common terminology for this sort of issue in general is "batch" vs. "interactive" running. We could make a more generic parameter "batch" which would silence not only progress bars but anything else that only makes sense in interactive mode (imagine something that pops up a plot for example). However, maybe the bar is the only thing we have like that in this code, so just having something to kill the bar is sufficient.

FYI after the refactor this bar drawing will no longer be internal to process_flashcam, it will be part of build_raw and will apply to any daq stream.

**Comment by jasondet** [comment]
Clint? check this with new progress bar.

**Comment by jasondet** [comment]
Left this as notes in the pygama trello, will follow up with this feature request there.

**Comment by gipert** [comment]
Also related to #246
