### ISSUE TITLE
Minimum supported Python version

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#178]
I realized that CI builds with Python versions 3.5 and 3.6 fail because of the `h5py>=3.2.0` constraint being unsatisfiable. Should we now explicitly support Python >= 3.7?

**Comment by iguinn** [comment]
Yes. There was some conversation in rocket chat a while back about making 3.7 the minimum; there are some other features that got introduced with 3.7 that people are using as well.

**Comment by gipert** [comment]
Ok, then this line here:

https://github.com/legend-exp/pygama/blob/master/.github/workflows/main.yml#L21

should be updated.
