### ISSUE TITLE
Support passing `None` to processors via JSON config

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#196]
We should make sure we support passing `None` as a processor argument in DSP config files. Currently, this
```js
"wf_cum": {
  "function": "cumsum",
  "module": "numpy",
  "args": ["wf_blsub", "None", "None", "wf_cum"],
  "kwargs": {"signature": "(n),(),()->(n)", "types": ["fii->f"]},
  "unit": "ADC"
}
```
Fails with
```
ProcessingChainError: Could not parse expression:
  None
```
While the JSON-supported `null` gives:
```
TypeError: type NoneType doesn't define __round__ method
```

**Comment by iguinn** [comment]
This should be solved in the refactor branch

**Comment by iguinn** [comment]
This has been tested and is confirmed to work on the refactor branch

**Comment by iguinn** [comment]
Now that refactor is merged, I'm closing this
