### ISSUE TITLE
Support processor functions where the output is not the last positional argument

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#198]
[`scipy.ndimage.gaussian_filter1d`](https://github.com/scipy/scipy/blob/v1.6.0/scipy/ndimage/filters.py#L211-L260)'s prototype is `gaussian_filter1d(input, sigma, axis=-1, order=0, output=None, mode="reflect", cval=0.0, truncate=4.0)`. At present, there's no way to use it as a processor, unless all arguments after `output` are left unspecified:
```json
"wf_gaus": {
    "function": "gaussian_filter1d",
    "module": "scipy.ndimage",
    "args": ["wf_blsub", "0.1*us", -1, 0, "wf_gaus"],
    "kwargs": {"signature": "(n),(),(),()->(n)", "types": ["ffii->f"]},
     "unit": "ADC"
},
```

**Comment by jasondet** [comment]
maybe create a dummy / wrapper function? or "processor_kwargs"-like field?

Ian to think about.

**Comment by iguinn** [comment]
This has been added on the refactor branch. The way it works is that in args you can pass an arg as an assignment equation, e.g.:
`"args": ["wf_blsub", "0.1*us", "out=wf_gaus"]`
The kwargs field is still reserved for key word arguments to the add_processor function including signature and types. In this case, you will have to pass these arguments, with size and type signatures pointing to the kwargs:
`"kwargs": {"signature": "(n),()->(n)", "types": ["ff->f"]}`
would work in this case. This was tested using:
```"wf_cum": {
    "function": "cumsum",
    "module": "numpy",
    "args": ["wf_blsub", 1, "out=wf_cum"],
    "kwargs": {"signature": "(n),()->(n)", "types": ["fi->f"]},
    "unit": "ADC"
}
```

**Comment by gipert** [comment]
Neat! Thanks Ian for adding this. I think we now support a wide range of third-party processors. We should add test cases for all these resolved issues, once we have a pulse generator.

**Comment by gipert** [comment]
@iguinn we support only numbers as keyword argument types, am I right? I'm trying to set `mode='reflect'` to `scipy.ndimage.gaussian_filter1d` but I get a
```
ValueError: could not convert string to float: 'reflect'
```
when instantiating `ProcessorManager`. How should non-numeric types be handled?

**Comment by gipert** [comment]
Ah wait, it works if I make sure that the output argument is always last, like: `"waveform", "0.1*us", "mode='reflect'", "output=wf_gaus"`. Is it intended?

**Comment by gipert** [comment]
> What about removing `pygama.dsp.processors.gaussian_filter1d` then?

I just realized the pygama version uses NumPy to perform the convolution. I assume this makes the processor more Numba-friendly. Correct?
