### ISSUE TITLE
Installing pygama requires -e flag?

### ISSUE THREAD

**Issue by CJNave613** [legend-exp/pygama#321]
I was helping an undergrad student install pygama and after having issues with Jupyter recognizing pygama modules, we deleted pygama from his home directory and re-cloned the repo. When trying to install pygama again via `pip install pygama --user`, we got the following error message:
`ERROR: could not find a version that satisfies the requirement pygama (from versions none)`
Eventually, we got the install to work properly with `pip install -e pygama --user` even though this student isn't planning on developing pygama. Is this `-e` flag now necessary to install pygama?

**Comment by gipert** [comment]
@CJNave613 is this still an issue?

**Comment by CJNave613** [comment]
@gipert Sorry, this slipped my mind. I'll give it a try this afternoon

**Comment by CJNave613** [comment]
I tried installing a new pygama instance on NERSC in my local directory and didn't have any issues excluding the `-e` flag (the install just defaulted to `pip install ./pygama`. I'm meeting with the student that was having this issue sometime this week so we can check if he still has the same problem or if specifying that it's a local directory fixes it. I'll report back here later this week. Thanks for the help Luigi!
