### ISSUE TITLE
pygama.egg-info

### ISSUE THREAD

**Issue by mmatteo** [legend-exp/pygama#329]
Installing pygama generates a directory  (`pygama/src/pygama.egg-info` ) inside the repository. Do we need it? 

I would like the installation step not to alter the input src directory.

**Comment by gipert** [comment]
The directory contains metadata and is automatically generated by setuptools the install step. I'm not expert enough to say whether it is really needed (I read that Python eggs have been deprecated in favor of Python wheels) nor how to disable this behavior...

Anyways, Python notoriously adds a lot of junk to the package source (think about caches). At least this goes outside the real source folder (`src/pygama`).
