### ISSUE TITLE
The "trim" option in analysis.histograms.get_hist is a bad idea

### ISSUE THREAD

**Issue by wisecg** [legend-exp/pygama#37]
We need to remove the "trim" option from the 
[`get_hist` convenience function:](https://github.com/legend-exp/pygama/blob/master/pygama/analysis/histograms.py#L12)

@jasondet pointed this out.  It can lead to errors in mistaking bin edges for bin centers, i.e. "binning is wrong by half a bin on the x-axis." 

To resolve this issue:
- We should fix the convenience function get_hist to remove the "trim" option
- We should scrub through pygama code and note instances where "trim" was set to true, remove the calls, and double-check that any plots made with "trim"==True are still OK.

**Comment by jasondet** [comment]
Looks like it was never set to true:
`
jasondet@Jasons-MBP pygama % grep -r "trim=" *    
apps/optimizer.py:        hE, xE, vE = ph.get_hist(t2df["e_ftp"], bins=1000, trim=False)
apps/calibration.py:        hE, xE, vE = ph.get_hist(t2df[ecal], range=(xlo, xhi), dx=xpb, trim=False)
experiments/mj60/optimizer.py:        hE, xE, vE = ph.get_hist(t2df["e_ftp"], range=(xlo, xhi), dx=xpb, trim=False)
pygama/analysis/histograms.py:def get_hist(np_arr, bins=None, range=None, dx=None, wts=None, trim=False):
`

**Comment by jasondet** [comment]
removed it.
