### ISSUE TITLE
"sh" is messed up from pygama.utils

### ISSUE THREAD

**Issue by wisecg** [legend-exp/pygama#38]
https://github.com/legend-exp/pygama/blob/fcdd95831dda9f0afe8330ca526ef44545c2c594/pygama/utils.py#L30

**Comment by jasondet** [comment]
Oh yeah, that function looks messed up. we should just remove it and use standard python packages (esp. subprocess.run()) to call shell commands from within python code

**Comment by jasondet** [comment]
removed in refactor branch.
