### ISSUE TITLE
nproc doesn't exist on MacOS; can't build docs with current Makefile

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/pygama#395]
https://github.com/legend-exp/pygama/blob/eb5363116ea8e4d592c6a66b38f3463bc3770bd7/docs/Makefile#L6

nproc doesn't exist on MacOS, so building using the default 'make' command fails with the present Makefile. Suggest removing the '-j$(shell nproc)' portion of the 'all' option to make this more streamlined for MacOS users.

**Comment by slwatkins** [comment]
For macOS users, we can create an alias in our .zshrc files (quoting below), but I think that the build doesn't really need to done on multiple cores, seems like overkill.

```
alias nproc="sysctl -n hw.logicalcpu"
```
