### ISSUE TITLE
Store the ADC bit depth as a waveform attribute

### ISSUE THREAD

**Issue by jasondet** [legend-exp/pygama#418]
i think we should store the ADC bit depth in the waveform object as one of its attributes. It matters for example when we presum: the presummer should be careful to choose an output int type with sufficient bit depth to store the presummed values. It should also update the bit depth attribute.

**Comment by SamuelBorden** [comment]
This has been implemented in the refactor branch in pull request #445

**Comment by gipert** [comment]
I just realized that PR was for `refactor`, why not `main`?

**Comment by SamuelBorden** [comment]
I didn't want to break anything in `dsp` and interrupt data production

**Comment by gipert** [comment]
Ok, I'll close this for now.
