### ISSUE TITLE
pygama needs a logo!

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#423]
Post suggestions, drafts or even sketches to help us select the logo that pygama deserves. The call is open to everyone, don't be shy! People with experience in graphic design are especially welcome if they want to propose or implement/improve others' ideas.

The logo should preferably be square (or at least not too elongated) and in vector format (SVG or PDF). To upload the image, attach it to the comment on GitHub. Vote by adding your reaction (click on the smiley face in the comment's upper right corner). Subscribe to this issue (button on the bar on the right) to be notified about new posts.

Happy designing!

<p align="center">
  <img src="https://i.pinimg.com/originals/a9/91/9c/a9919cebd23ce8f21d74c974ac919c2f.jpg" width="400"/>
<p/>

**Comment by sagitta42** [comment]
Might try my hands at logo design, although I have no experience and only GIMP. My idea for a logo would be something minimalistic and not even necessarily including the words "pygama". Should definitely be Python blue and yellow colors. Could be pyjamas, or a "gamma" symbol, or a "gamma" symbol with "py" in Python font before the gamma

**Comment by purgenetik** [comment]
Some execises:
pygama dress-like 
![image](https://user-images.githubusercontent.com/9008124/208950635-4fe80597-0b4d-47a9-b230-42def985e5c6.png)
or LEGENDary strings...
![image](https://user-images.githubusercontent.com/9008124/208950878-3143edbf-49df-4753-983c-7ff06a8b6eba.png)
or geometric constructions that demonstrate the modular principle of the software, which allows you to assemble a useful product from bricks (and objects of other shape) 
![image](https://user-images.githubusercontent.com/9008124/208950943-538150cc-d48b-45e9-9c55-884b970a05cf.png)

**Comment by purgenetik** [comment]
It's also a good idea for Eli to use Greek letters. She suggested a large gamma, but it seems to me that a small one is better, it turns out a very scientific logo, moreover, a logo for particle physics, where there is no way without pi (mesons)
![image](https://user-images.githubusercontent.com/9008124/208956561-e9535e4c-3d0e-4949-a1ab-e54fe60d97aa.png)

**Comment by jasondet** [comment]
here’s the version I made for fun at the collab mtg
![pygama_logo](https://user-images.githubusercontent.com/2238942/208986679-2c98a40c-193a-4a63-8c2d-4894bcf5c702.png)

**Comment by slwatkins** [comment]
![pygama_draft](https://user-images.githubusercontent.com/35979561/211164053-d946a113-5772-4dfc-839f-a4f31c56a117.svg)

Played around a little bit with the idea of the legend dragon with pajamas - font and pajamas still need work! Using the same colors as the legend logo, and I vectorized the Slack emoji (do we have a vectorized version that I can use?)

**Comment by slwatkins** [comment]
> It's also a good idea for Eli to use Greek letters. She suggested a large gamma, but it seems to me that a small one is better, it turns out a very scientific logo, moreover, a logo for particle physics, where there is no way without pi (mesons) 

Just came across this org/repo: https://github.com/gammapy --- they use this idea, so I think we have to rule this one out!

**Comment by MoritzNeuberger** [comment]
I thought Jason's idea was cute and took it as inspiration for a little rainy afternoon Inkscape doodling. This was the result.
[pygama_logo_v3.pdf](https://github.com/legend-exp/pygama/files/13228623/pygama_logo_v3.pdf)
![pygama_logo_v3](https://github.com/legend-exp/pygama/assets/31659079/5cccb0aa-1382-4f50-a199-c7cf9361b275)

**Comment by gipert** [comment]
Just a concept, to be improved!

![pygama](https://github.com/legend-exp/pygama/assets/20358192/c6dd5292-22f1-41ab-bae7-c01798b9e715)

**Comment by jasondet** [comment]
My sister in law is a graphic designer and I asked her to take a stab at it. She first came up with these drafts. Her 10 year old son had some ideas too!
![draftlogo1](https://github.com/legend-exp/pygama/assets/2238942/3446064e-880c-479e-86e1-82a74c0ac447)
![draftlogo2](https://github.com/legend-exp/pygama/assets/2238942/e8287f6b-aee7-4fdb-b458-cd0168d6e096)
![draftlogo3](https://github.com/legend-exp/pygama/assets/2238942/bebdd84e-acd2-455a-bfa5-6f1e27ded3d8)
![draftlogo4](https://github.com/legend-exp/pygama/assets/2238942/dad7ec8c-c7eb-47dd-89b2-09c98c020706)

**Comment by jasondet** [comment]
Here's variations on the first of those with more pyjama features and legend colors
![image1](https://github.com/legend-exp/pygama/assets/2238942/448b8e3a-db3f-4ec2-9cc1-ace92581080a)
![image2](https://github.com/legend-exp/pygama/assets/2238942/7cc41cb8-7116-4122-8e26-5af31cda9514)

**Comment by jasondet** [comment]
I've been asked to make individually likeable posts for the images in the previous 2 posts. Please move your votes to the one you like.

**Comment by jasondet** [comment]
![283913058-3446064e-880c-479e-86e1-82a74c0ac447](https://github.com/legend-exp/pygama/assets/2238942/a81e5a91-b302-4284-8783-70f31e37d3fd)

**Comment by jasondet** [comment]
![283913064-e8287f6b-aee7-4fdb-b458-cd0168d6e096](https://github.com/legend-exp/pygama/assets/2238942/7e55d53b-0462-49a6-a92f-f89e2b881428)

**Comment by jasondet** [comment]
![283913217-448b8e3a-db3f-4ec2-9cc1-ace92581080a](https://github.com/legend-exp/pygama/assets/2238942/d7784e1c-2923-4ddb-8379-0a359055e329)

**Comment by jasondet** [comment]
![Uploading 283913222-7cc41cb8-7116-4122-8e26-5af31cda9514.png…]()

**Comment by jasondet** [comment]
![283913222-7cc41cb8-7116-4122-8e26-5af31cda9514](https://github.com/legend-exp/pygama/assets/2238942/0e0cfbe4-7f00-4408-86c3-08fb7cc05a60)

**Comment by sofia-calgaro** [comment]
The EC dinner had quite a fruitful idea yesterday night, thanks to everybody who contributed to this idea (if someone wants to read more information on the history of human alphabets, here's a short source https://publicdomainreview.org/collection/the-human-alphabet)

![1702508859922](https://github.com/legend-exp/pygama/assets/77326044/7f603a98-ebc4-455e-a54d-a04dfb6aeadd)

**Comment by jasondet** [comment]
From Yuen-Dat Chan
![pygama_logo](https://github.com/legend-exp/pygama/assets/2238942/7e03a58d-59e9-4b2b-a274-34de3b7be74c)

**Comment by jasondet** [comment]
And the winner is:
![pygama_logo](https://github.com/legend-exp/pygama/assets/2238942/ec435c93-5e8d-4434-8343-516e68308a00)
