### ISSUE TITLE
Support YAML configuration files

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#548]
We should go through the codebase and swap `json.load()` calls with a generic loader, e.g.:

https://github.com/legend-exp/pylegendmeta/blob/main/src/legendmeta/utils.py

**Comment by gipert** [comment]
`build_hit()` and `build_evt()` already support YAML configs. `DataLoader()` and `pygama.pargen` still need to be updated.

**Comment by ggmarshall** [comment]
I don't think pargen has any json loading in it anyway, this is handled in the dataflow

**Comment by gipert** [comment]
Ok, I'll close this then.
